"""empty message

Revision ID: 3252d0877989
Revises: None
Create Date: 2015-11-20 17:00:21.760033

"""

# revision identifiers, used by Alembic.
revision = '3252d0877989'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id_c', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_c')
    )
    op.create_table('users',
    sa.Column('id_u', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_u')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('contracts')
    ### end Alembic commands ###
